"""add_artifact_kind_created_composite_index

Revision ID: 31992a96f15c
Revises: 99f725157583
Create Date: 2026-04-20 20:08:43.726585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31992a96f15c'
down_revision: Union[str, Sequence[str], None] = '99f725157583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index('ix_artifacts_kind_created_at', ['kind', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index('ix_artifacts_kind_created_at')

    # ### end Alembic commands ###
