"""add_oauth_connections_and_scheduled_posts

Revision ID: 4d9b9c14491d
Revises: b1c4f7a9d3e2
Create Date: 2026-04-18 19:45:49.366747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9b9c14491d'
down_revision: Union[str, Sequence[str], None] = 'b1c4f7a9d3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_account_id', sa.String(length=256), nullable=True),
    sa.Column('external_account_name', sa.String(length=256), nullable=True),
    sa.Column('tokens_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform')
    )
    op.create_table('scheduled_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('reel_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('external_video_id', sa.String(length=256), nullable=True),
    sa.Column('external_url', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notify_subscribers', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_posts')
    op.drop_table('oauth_connections')
    # ### end Alembic commands ###
