"""add fit_mode, source_language, detected_language to jobs

Revision ID: ad0e5af03bfc
Revises: b375ed0ea0a0
Create Date: 2026-04-16 14:13:34.590071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0e5af03bfc'
down_revision: Union[str, Sequence[str], None] = 'b375ed0ea0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'fit_mode',
                sa.String(length=8),
                nullable=False,
                server_default='fill',
            )
        )
        batch_op.add_column(
            sa.Column(
                'source_language',
                sa.String(length=16),
                nullable=False,
                server_default='auto',
            )
        )
        batch_op.add_column(
            sa.Column('detected_language', sa.String(length=16), nullable=True)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('detected_language')
        batch_op.drop_column('source_language')
        batch_op.drop_column('fit_mode')

    # ### end Alembic commands ###
