"""publer_scheduler_schema

Revision ID: eb6d1b814c95
Revises: 31992a96f15c
Create Date: 2026-04-23 19:24:44.075066

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eb6d1b814c95'
down_revision: str | Sequence[str] | None = '31992a96f15c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop legacy YouTube/IG OAuth scheduler tables first.
    op.drop_table('scheduled_posts')
    op.drop_table('oauth_connections')
    op.create_table('account_profiles',
    sa.Column('publer_account_id', sa.String(length=24), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('tone', sa.Text(), nullable=False),
    sa.Column('default_hashtags_json', sa.JSON(), nullable=False),
    sa.Column('banned_words_json', sa.JSON(), nullable=False),
    sa.Column('cta_style', sa.Text(), nullable=False),
    sa.Column('max_caption_length', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('publer_account_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('time_of_day', sa.String(length=8), nullable=False),
    sa.Column('dates_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caption_presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('account_id', sa.String(length=24), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_profiles.publer_account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caption_presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caption_presets_account_id'), ['account_id'], unique=False)

    op.create_table('schedule_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('reel_artifact_id', sa.Integer(), nullable=False),
    sa.Column('publer_account_id', sa.String(length=24), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('hashtags_json', sa.JSON(), nullable=False),
    sa.Column('applied_preset_ids_json', sa.JSON(), nullable=False),
    sa.Column('scheduled_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('publer_media_id', sa.String(length=32), nullable=True),
    sa.Column('publer_job_id', sa.String(length=32), nullable=True),
    sa.Column('publer_post_id', sa.String(length=32), nullable=True),
    sa.Column('publer_post_url', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['schedule_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publer_account_id'], ['account_profiles.publer_account_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reel_artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'reel_artifact_id', 'publer_account_id', name='uq_assignment_campaign_reel_account')
    )
    with op.batch_alter_table('schedule_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_assignments_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_assignments_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_assignments_publer_account_id'), ['publer_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_assignments_reel_artifact_id'), ['reel_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_assignments_status'), ['status'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_jobs_project_id_projects', 'projects', ['project_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_project_id_projects', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))
        batch_op.drop_column('project_id')

    op.create_table('oauth_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_account_id', sa.String(length=256), nullable=True),
    sa.Column('external_account_name', sa.String(length=256), nullable=True),
    sa.Column('tokens_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform')
    )
    op.create_table('scheduled_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('reel_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('external_video_id', sa.String(length=256), nullable=True),
    sa.Column('external_url', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notify_subscribers', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_schedule_assignments_reel_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_assignments_publer_account_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_assignments_job_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_assignments_campaign_id'))

    op.drop_table('schedule_assignments')
    with op.batch_alter_table('caption_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caption_presets_account_id'))

    op.drop_table('caption_presets')
    op.drop_table('schedule_campaigns')
    op.drop_table('projects')
    op.drop_table('account_profiles')
    # ### end Alembic commands ###
